### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [JSSpaulding/rcrimeanalysis#2]
Email April 1:

rcrimeanalysis has strong dependence on at least one of `rgdal`, `rgeos` or
`maptools`, but does not seem to use any functionality in code. The usage
may have been in `raster`, which now uses `terra` instead, or may be in
examples or vignettes. Please move all use of `rgdal`, `rgeos` or
`maptools` to Suggests: and protect any use against these packages not
being present. The packages will be archived in October 2023. See
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and
perhaps view
https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_
YmAh4pq9&index=1.

Best wishes,

On Thu, 15 Dec 2022, Roger Bivand wrote:

> Dear Maintainer,
>
> rcrimeanalysis depends on (depends, imports or suggests) **raster** and
> one or more of the retiring packages **rgdal**, **rgeos** or **maptools**
> (https://r-spatial.org/r/2022/04/12/evolution.html,
> https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster**
> `3.6.3`, all use of external FOSS library functionality has been
> transferred to **terra**, making the retiring packages very likely
> redundant. It would help greatly if you could remove dependencies on the
> retiring packages as soon as possible.

Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

Removing retiring packages from DESCRIPTION, NAMESPACE and spurious roxygen tags, and running CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path gives this log:
[00check.log](https://github.com/JSSpaulding/rcrimeanalysis/files/11352543/00check.log)

**Comment by JSSpaulding** [comment]
'rgdal' dependency removed. rcrimeanalysis 0.4.3. submitted to CRAN
